    name: Deploy Astro to GitHub Pages

    on:
      push:
        branches: [main]

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '20' # Or your desired Node.js version

          - name: Install dependencies
            run: npm ci # Or yarn install / pnpm install

          - name: Build Astro project
            run: npm run build # Or yarn build / pnpm build

          - name: Deploy to GitHub Pages
            uses: withastro/action@v0.2.1 # Or the latest version
            with:
              path: ./dist # Path to your built Astro project
